version: "3"

services:
  wordpress:
    container_name: "local-wordpress"
    depends_on:
      - database
    image: "wordpress:latest"
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: "database:3306"
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: rosettistarr
    volumes:
      - "../src:/var/www/html"

  database:
    image: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=rosettistarr
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - wordpress:/var/lib/mysql
volumes:
  wordpress:
